# Generated by Django 3.1.13 on 2021-10-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='duration',
            field=models.PositiveSmallIntegerField(default=30, help_text='Duration in minutes'),
        ),
    ]
